paths:
  /api/products/:
    get:
      summary: Get all products
      tags:
        - Products
      responses:
        "200":
          description: Returns all products
        "500":
          description: Internal server error
    post:
      summary: Create a product
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: Returns a product
        "500":
          description: Internal server error

  /api/products/{id}:
    get:
      summary: Get a product
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the product
          schema:
            type: string
      responses:
        "200":
          description: Returns a product
        "500":
          description: Internal server error
    put:
      summary: Update a product
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the product
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "200":
          description: Returns a product
        "500":
          description: Internal server error
    delete:
      summary: Delete a product
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the product
          schema:
            type: string
      responses:
        "200":
          description: Returns a product
        "500":
          description: Internal server error

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: The auto-generated id of the product
        name:
          type: string
          description: Product name
        category:
          type: string
          description: Product category
        price:
          type: number
          description: Product price
        stock:
          type: number
        image:
          type: string
          description: Product image
        owner:
          type: string
          description: Product owner
      example:
        _id: ObjectId("6568c2c6a399c47c8628e289")
        name: Product name
        category: Product category
        price: 10
        stock: 10
        image: Product image
        owner: test@test
